local fw = require("neotest-scala.framework")

describe("framework", function()
  describe("get_framework_class", function()
    describe("known frameworks", function()
      it("returns utest module", function()
        local mod = fw.get_framework_class("utest")
        assert.is_not_nil(mod)
        assert.is_function(mod.build_command)
      end)

      it("returns munit module", function()
        local mod = fw.get_framework_class("munit")
        assert.is_not_nil(mod)
        assert.is_function(mod.build_command)
      end)

      it("returns scalatest module", function()
        local mod = fw.get_framework_class("scalatest")
        assert.is_not_nil(mod)
        assert.is_function(mod.build_command)
      end)

      it("returns specs2 module", function()
        local mod = fw.get_framework_class("specs2")
        assert.is_not_nil(mod)
        assert.is_function(mod.build_command)
      end)

      it("returns zio-test module", function()
        local mod = fw.get_framework_class("zio-test")
        assert.is_not_nil(mod)
        assert.is_function(mod.build_command)
      end)
    end)

    describe("unknown frameworks", function()
      it("returns nil for 'unknown'", function()
        assert.is_nil(fw.get_framework_class("unknown"))
      end)

      it("returns nil for 'anything_else'", function()
        assert.is_nil(fw.get_framework_class("anything_else"))
      end)

      it("returns nil for empty string", function()
        assert.is_nil(fw.get_framework_class(""))
      end)
    end)
  end)

  describe("constants", function()
    it("TEST_PASSED is 'passed'", function()
      assert.are.equal("passed", fw.TEST_PASSED)
    end)

    it("TEST_FAILED is 'failed'", function()
      assert.are.equal("failed", fw.TEST_FAILED)
    end)

    it("TEST_PASSED is set in _G", function()
      assert.are.equal(fw.TEST_PASSED, _G.TEST_PASSED)
    end)

    it("TEST_FAILED is set in _G", function()
      assert.are.equal(fw.TEST_FAILED, _G.TEST_FAILED)
    end)
  end)
end)
